name:                bloom-filter
version:             0.1.0.0
github:              "nikitakarandej/bloom-filter"
license:             MIT
author:              "Nick Karandejs"
maintainer:          "nick.karandejs@gmail.com"
copyright:           "2018 Nick Karandejs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nikitakarandej/bloom-filter#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.2
- mtl >= 2.2.1
- bytestring == 0.10.8.2
- deepseq == 1.4.3.0
- parallel == 3.2.1.1
- time == 1.8.0.2

include-dirs: src/cbits
c-sources: src/cbits/lookup3.c
cc-options: -O3
install-includes: lookup3.h

library:
  source-dirs: src

executables:
  bloom-filter-exe:
    main:                WordTest.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - bloom-filter

tests:
  bloom-filter-test:
    main:                BloomCheck.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bloom-filter
    - QuickCheck == 2.10.1
    - random == 1.1
